canal_tp_sam_ecore_application_manager_choose_application:
    path: /change/{application}
    defaults: { _controller: CanalTPSamEcoreApplicationManagerBundle:Application:change }

canal_tp_sam_ecore_application_manager_toolbar:
    path: /toolbar
    defaults: { _controller: CanalTPSamEcoreApplicationManagerBundle:Application:toolbar }

canal_tp_sam_show_changelog:
    path:  /{canonicalName}/CHANGELOG.md
    defaults: { _controller: "CanalTPSamEcoreApplicationManagerBundle:Application:changelog" }
    requirements:
        canonicalName: -?[a-zA-Z]*
